### ISSUE TITLE
Footnote spacing problem with multiple footnotes

### ISSUE THREAD

**Issue by VincentSch4rf** [mas-group/beamer-template#4]
# Description
When using `\footcite` or generally `\footnote` it will add a space of `4ex` after each of the footnotes. While this is necessary in order for the footnotes not to be overlaying the footline set via the `beamertemplate` footline, it only works as intended for **one** footline. With multiple footnotes the `4ex` space is not only inserted after the last footnote but after each, resulting in slides like this:
![image](https://user-images.githubusercontent.com/28391665/124277176-0b13b780-db45-11eb-9c52-79c3a65bd314.png)

Removing the `vspace` added as a command overwrite https://github.com/mas-group/beamer-template/blob/40197775694d12aec3b5e24a4177f9652044c549/theme/beamerinnerthemehbrs.sty#L9

removes the space between the footnotes, but unfortunately also moves them into the logos part of the template:
![image](https://user-images.githubusercontent.com/28391665/124277534-6cd42180-db45-11eb-96a0-56c1c1b26973.png)

# Solution
Removing the `vspace` and instead adding
```tex
\patchcmd{\beamer@calculateheadfoot}{\advance\footheight by 4pt}{\advance\footheight by 5ex}{}{}
```
the space as a command patch directly to the layout of the footline height fixes the problem.
![image](https://user-images.githubusercontent.com/28391665/124322967-b857f100-db80-11eb-82ce-4dd2b692cd83.png)

**Comment by alex-mitrevski** [comment]
Resolved by https://github.com/mas-group/beamer-template/pull/5. Thanks @VincentSch4rf!
